backend/config/routes.rb
Rails.application.routes.draw do
  #devise_for :users, :skip => [:sessions, :passwords, :registrations]
  scope path: '/api' do
    api_version(module: "V1", path: { value: "v1" }, defaults: { format: 'json' }) do
      devise_for :users, controllers: {
        registrations: 'v1/custom_devise/registrations',
        sessions: 'v1/custom_devise/sessions',
      }

      get 'chatrooms', to: "rooms#index", as: :rooms_index #Check
      post 'chatrooms', to: "rooms#create", as: :new_room #Check
      get 'chatrooms/my-rooms', to: "rooms#my_rooms", as: :my_rooms #Check
      post 'chatrooms/join', to: "rooms#join_room", as: :join_room #Midle Check (Missing Action Cable)
      get 'chatrooms/:id', to: "rooms#show", as: :show_room #Check
      delete 'chatrooms/:id', to: "rooms#destroy", as: :delete_room #Check

      get 'chatrooms/:id/messages', to: "messages#index", as: :messages_room
      post 'chatrooms/:id/messages', to: "messages#create", as: :create_message_room
    end
  end
  # get 'home/index'
  # devise_for :user, controllers: {
  #   sessions: 'users/sessions',
  #   registrations: 'users/registrations'
  # }
  # get 'chatrooms/', to: "rooms#index", as: :rooms_index
  # post 'chatrooms', to: "rooms#create", as: :new_room
  # get 'chatrooms/my-rooms', to: "rooms#my_rooms", as: :my_rooms
  # post 'chatrooms/join', to: "rooms#join_room", as: :join_room
  # get 'chatrooms/:chatroom', to: "rooms#show", as: :show_room
  # delete 'chatrooms/:chatroom', to: "rooms#destroy", as: :delete_room

  # post 'messages/new', to: "messages#create", as: :new_message

  mount ActionCable.server, at: '/cable'

  root 'home#index'
end

backend/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :get_create_params, only: [:create]
    before_action :get_my_rooms, only: [:index, :my_rooms]
    before_action :set_join_room, only: [:join_room]
    before_action :set_room, only: [:update, :show, :destroy]
    
    def index
        av_rooms = Chatroom.where({private: false}).to_a
        @rooms = @my_rooms + av_rooms.difference(@my_rooms.to_a)
        @r_id = get_room_id()
    end

    def my_rooms
        @rooms = @my_rooms
        @r_id = get_room_id()
    end

    def join_room
        if @room
            if Member.create({user_id: current_user.id, chatroom_id: @room.id})
                msg = Message.create({user_id: 0, chatroom_id: @room.id, system: true, body: "@#{current_user.nickname} se ha unido al chat!"})
                date = msg.created_at
                ActionCable.server.broadcast(
                    "messages_#{@room.id}",
                    server: true,
                    data: {body: msg.body, created_at: [date.day, date.month, date.year, date.hour, date.min]}
                  )
                redirect_to show_room_path(@room)
            else
                session[:alert] = "No se ha podido ingresar a la sala"
            redirect_to rooms_index_path
            end
        else
            session[:alert] = "No se ha podido encontrar la sala"
            redirect_to rooms_index_path
        end
    end

    def show
        if @room and Member.find_by({user_id: current_user.id, chatroom_id: @room.id})
            @messages = Message.where({chatroom_id: @room.id})
            render "show"
        else
            session[:alert] = "No se ha podido acceder a la sala."
            redirect_to rooms_index_path
        end
    end

    def destroy
        if @room
            if @room.destroy()
                session[:notice] = "Sala cerrada correctamente."
                redirect_to my_rooms_path
            else
                session[:alert] = "Ha ocurrido un error al cerrar la sala."
                redirect_to my_rooms_path
            end
        else
            session[:alert] = "No se ha podido cerrar la sala."
            redirect_to my_rooms_path
        end
    end

    def create
        @new_room_attr[:user_id] = current_user.id
        @room = Chatroom.create(@new_room_attr)
        Member.create({user_id: current_user.id, chatroom_id: @room.id})

        redirect_to rooms_index_path
    end
    
    protected

    def set_room
        @room = Chatroom.find_by({id: params[:chatroom]})
    end

    def set_join_room
        @room = Chatroom.find_by({room_code: params.require(:chatroom).permit(:chatroom_code)[:chatroom_code]})
    end

    def get_my_rooms
        @my_rooms = Chatroom.includes(:members).where(members: {user_id: current_user.id})
    end

    def get_create_params
        @new_room_attr = params.require(:chatroom).permit(:name, :private, :description, :room_code)
    end

    def get_room_id
        @r_id = rand(1000..9999)
        while Chatroom.find_by({room_code: @r_id})
            @r_id = rand(1000..9999)
        end
        return @r_id
    end
end

backend/app/helpers/rooms_helper.rb
module RoomsHelper
end

backend/app/views/rooms/_room_list.html.erb
<div class="room-index px-3">
<button type="button" class="btn btn-success" id="btn-new-room" data-toggle="modal" data-target="#join-room-modal">Unirse a una Sala</button>
<button type="button" class="btn btn-outline-success" id="btn-new-room" data-toggle="modal" data-target="#new-room-modal">Crear Sala</button>
<hr/>
<div class="rooms-list">
<% @rooms.each do |r| %>
    <div class="card mb-2">
        <div class="card-header">
            Código: <%= r.room_code %>
        </div>
        <div class="card-body">
            <h5 class="card-title"><%= r.name %></h5>
            <p class="card-text"><%= r.description %></p>
            <div class="row">
            <% if @my_rooms.include? r %>
                <a role="button" class="btn btn-primary mx-2" href=<%= show_room_path(r) %>>Abrir Chat</a>
            <% else %>
                <%= form_with(url: join_room_path, method: "post", remote: true) do |f| %>
                    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
                    <%= hidden_field(:chatroom, :chatroom_code, value: r.room_code) %>
                    <button type="submit" class="btn btn-success mx-2">Unirse</button>
                <% end %>
            <% end %>
            <% if r.user_id == current_user.id %>
                <%= form_with(url: delete_room_path(r), method: "delete", remote: true, class: "form-inline") do |f| %>
                    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
                    <button type="submit" class="btn btn-outline-danger mx-2">Cerrar Sala</button>
                <% end %>
            <% end %>
            </div>
        </div>
    </div>
<% end %>
</div>
</div>
<!-- Modal New room -->
<div class="modal fade" id="new-room-modal" tabindex="-1" aria-labelledby="newRoomModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newRoomModalLabel">Crear Nueva Sala</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with( url: new_room_path, method: "post", remote: true) do |f| %>
            <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
            <div class="form-group">
                <%= label_tag(:name, "Nombre de la sala") %>
                <%= text_field(:chatroom, :name, class: "form-control", required: "") %>
            </div>
            <div class="form-group">
                <%= label_tag(:description, "Descipción") %>
                <%= text_area(:chatroom, :description, class: "form-control", placeholder: "(recomendado)") %>
            </div>
            <div class="form-group row">
                <%= label_tag(:room_code, "Código de sala:", class: "col-sm-4 col-form-label") %>
                <%= text_field(:chatroom, :room_code, readonly: true, class: "col-sm-8 form-control-plaintext", value: @r_id) %>
            </div>
            <div class="form-check">
                <%= check_box(:chatroom, :private, class: "form-check-input") %>
                <%= label_tag(:private, "Hacer sala privada", class: "form-check-label") %>
                <small id="privateHelp" class="form-text text-muted">Solo se prodrá acceder con el código.</small>
            </div>

            <div class="form-group ml-auto mt-4">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-primary">Crear</button>
            </div>
            <% end %>
        
      </div>
    </div>
  </div>
</div>

<!-- Modal Join room -->
<div class="modal fade" id="join-room-modal" tabindex="-1" aria-labelledby="joinRoomModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="joinRoomModalLabel">Unirse a Sala</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(url: join_room_path, method: "post", remote: true) do |f| %>
            <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
            <div class="form-group row">
                <%= label_tag(:chatroom_code, "Código de sala:", class: "col-sm-4 col-form-label") %>
                <%= text_field(:chatroom, :chatroom_code, class: "col-sm-8 form-control", required: "") %>
            </div>
            <div class="form-group ml-auto mt-4">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-success">Unirse</button>
            </div>
            <% end %>
        
      </div>
    </div>
  </div>
</div>

backend/app/views/rooms/index.html.erb
<title>Salas de Chat - Textgram</title>

<h1>Salas Disponibles</h1>

<%= render  "rooms/room_list" %>

backend/app/views/rooms/my_rooms.html.erb
<title>Mis Salas - Textgram</title>

<h1>Mis Salas</h1>

<%= render  "rooms/room_list" %>

backend/app/views/rooms/show.html.erb
<%= action_cable_meta_tag %>

<%  prev_date = nil %>

<title><%= @room.name %> - Textgram</title>

<div class="chat-container px-2">
<h1><%= @room.name %></h1>
<hr/>
<div class="chatbox" data-channel-subscribe="room" data-room-id="<%= @room.id %>" data-current-user="<%= current_user.nickname %>" id="chatbox">
<% @messages.each do |m| %>
    <% if not prev_date or m.created_at.midnight > prev_date  %>
       <div class="server-msg rounded-pill bg-info text-center w-25 mx-auto text-white my-1" data-date="<%= m.created_at.strftime('%d-%m-%y') %>" ><%= m.created_at.strftime('%d-%m-%y') %></div>        
        <% prev_date = m.created_at.midnight %>
    <% end %>
    <% if m.system %>
        <div class="server-msg rounded-pill bg-secondary text-center w-25 mx-auto my-1 text-wrap"><%= m.body %></div>
    <% else %>
    <% if m.user_id == current_user.id %>
        <div class="my-msg bg-success ml-auto my-1 px-3 py-1">
            <div clas="msg-container">
                <div class="msg-body text-white text-wrap">
                    <%= m.body %>
                </div>
                <div class="msg-foot text-right text-white-50 text-small">
                    <%= m.created_at.strftime('%H:%M') %>
                </div>
            </div>
        </div>
    <% else %>
        <div class="other-msg bg-primary my-1 px-3 py-1">
            <div clas="msg-container">
                <div class="msg-head text-left">
                    <%= m.username %>
                </div>
                <div class="msg-body text-white text-wrap">
                    <%= m.body %>
                </div>
                <div class="msg-foot text-right text-white-50 text-small">
                    <%= m.created_at.strftime('%H:%M') %>
                </div>
            </div>
        </div>
    <% end %>
    <% end %>
<% end %>
</div>

<form id="new-msg-form" data-remote="false">
    <input name="authenticity_token" type="hidden" value=<%= form_authenticity_token %>>
    <input type="hidden" name="message[chatroom_id]" value=<%= @room.id %>>
    <div class="form-group row mt-3">
        <div class="col-9 col-sm-11">
            <input class="form-control" type="text" name="message[body]" id="message_body">
        </div>
        <div class="col-3 col-sm-1">
            <button type="submit" class="btn btn-success">Enviar</button>
        </div>
    </div>
</form>
</div>