backend/config/routes.rb
Rails.application.routes.draw do
  #devise_for :users, :skip => [:sessions, :passwords, :registrations]
  scope path: '/api' do
    api_version(module: "V1", path: { value: "v1" }, defaults: { format: 'json' }) do
      devise_for :users, controllers: {
        registrations: 'v1/custom_devise/registrations',
        sessions: 'v1/custom_devise/sessions',
      }

      get 'chatrooms', to: "rooms#index", as: :rooms_index #Check
      post 'chatrooms', to: "rooms#create", as: :new_room #Check
      get 'chatrooms/my-rooms', to: "rooms#my_rooms", as: :my_rooms #Check
      post 'chatrooms/join', to: "rooms#join_room", as: :join_room #Midle Check (Missing Action Cable)
      get 'chatrooms/:id', to: "rooms#show", as: :show_room #Check
      delete 'chatrooms/:id', to: "rooms#destroy", as: :delete_room #Check

      get 'chatrooms/:id/messages', to: "messages#index", as: :messages_room
      post 'chatrooms/:id/messages', to: "messages#create", as: :create_message_room
    end
  end
  # get 'home/index'
  # devise_for :user, controllers: {
  #   sessions: 'users/sessions',
  #   registrations: 'users/registrations'
  # }
  # get 'chatrooms/', to: "rooms#index", as: :rooms_index
  # post 'chatrooms', to: "rooms#create", as: :new_room
  # get 'chatrooms/my-rooms', to: "rooms#my_rooms", as: :my_rooms
  # post 'chatrooms/join', to: "rooms#join_room", as: :join_room
  # get 'chatrooms/:chatroom', to: "rooms#show", as: :show_room
  # delete 'chatrooms/:chatroom', to: "rooms#destroy", as: :delete_room

  # post 'messages/new', to: "messages#create", as: :new_message

  mount ActionCable.server, at: '/cable'

  root 'home#index'
end

backend/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- RAILS style js tags -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'app_javascript' %>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href=<%= root_path %>>Textgram</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <% if current_user %>
            <li class="nav-item">
                <a class="nav-link" href=<%= rooms_index_path %>>Salas de Chat</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href=<%= my_rooms_path %>>Mis Salas</a>
            </li>
            <% end %>
        </ul>
        <ul class="navbar-nav ml-auto">
        <% if current_user %>
            <li class="nav-item">Hola! @<%= current_user.nickname %></li>
            <li class="nav-item">
            <%= form_tag( destroy_user_session_path , remote: false, method: :delete) do |f| %>
                <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> />
                <button type="submit" role="button" class="btn btn-outline-danger mx-1">Cerrar Sesión</button>
            <% end %>
            </li>
        <% else %>
            <li class="nav-item">
            <a id="log-in" role="button" class="btn btn-link-primary mx-1" href=<%= new_user_session_path %> >Iniciar Sesión</a>
            </li>
            <li class="nav-item">
            <a id="sign-up" role="button" class="btn btn-primary mx-1" href=<%= new_user_registration_path %>>Registrarse</a>
            </li>
        <% end %>
        </ul>
    </div>
    </nav>
    <div class="alerts-container">
    <% if notice %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <% end
    if alert
    %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <% end %>
    <% if session[:notice] %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= session[:notice] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <% 
    session[:notice] = nil
    end
    if session[:alert]
    %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= session[:alert] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <% 
    session[:alert] = nil
    end %>
    </div>

    <%= yield %>
  </body>
</html>